server:
  port: 8081
spring:
  application:
    name: keycloak-spring-boot


  datasource:
    url: jdbc:postgresql://appdb:5432/postgres #FOR LOCALHOST: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/keycloak-spring-boot/protocol/openid-connect/certs #FOR LOCALHOST: http://localhost:8080/auth/realms/keycloak-spring-boot/protocol/openid-connect/certs

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect